"""add_serenity_integration_tables_l1

Revision ID: 2942cd845590
Revises: af307f2c5e72
Create Date: 2026-08-02 17:37:25.038985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2942cd845590'
down_revision: Union[str, Sequence[str], None] = 'af307f2c5e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_serenity_scores',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('bottleneck_score', sa.Integer(), nullable=True),
    sa.Column('bom_pct', sa.Float(), nullable=True),
    sa.Column('contracted_arr_multiple', sa.Float(), nullable=True),
    sa.Column('mag7_customer_count', sa.Integer(), nullable=True),
    sa.Column('gaap_gross_margin', sa.Float(), nullable=True),
    sa.Column('is_pre_ramp', sa.Boolean(), nullable=True),
    sa.Column('active_atm_pct_of_mc', sa.Float(), nullable=True),
    sa.Column('financing_tier', sa.String(length=2), nullable=True),
    sa.Column('short_interest_pct', sa.Float(), nullable=True),
    sa.Column('is_profitable', sa.Boolean(), nullable=True),
    sa.Column('institutional_holdings_delta_30d', sa.Float(), nullable=True),
    sa.Column('serenity_tier', sa.String(length=2), nullable=True),
    sa.Column('anti_pattern_flags', sa.Text(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('auto_avoid', sa.Boolean(), nullable=False),
    sa.Column('domain_tags', sa.Text(), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('discovery_serenity_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_serenity_scores_auto_avoid'), ['auto_avoid'], unique=False)
        batch_op.create_index('ix_serenity_score_total_desc', ['total_score'], unique=False)

    op.create_table('serenity_backtest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('signal_date', sa.String(length=10), nullable=False),
    sa.Column('price_at_signal', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_10d', sa.Float(), nullable=True),
    sa.Column('return_30d', sa.Float(), nullable=True),
    sa.Column('return_60d', sa.Float(), nullable=True),
    sa.Column('return_180d', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serenity_backtest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serenity_backtest_signal_id'), ['signal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_serenity_backtest_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_serenity_backtest_ticker_date', ['ticker', 'signal_date'], unique=False)

    op.create_table('serenity_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('thesis_type', sa.String(length=30), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extracted_reasoning', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serenity_signals', schema=None) as batch_op:
        batch_op.create_index('ix_serenity_signal_sentiment_time', ['sentiment', 'extracted_at'], unique=False)
        batch_op.create_index('ix_serenity_signal_ticker_time', ['ticker', 'extracted_at'], unique=False)
        batch_op.create_index('ix_serenity_signal_tweet_ticker', ['tweet_id', 'ticker'], unique=True)
        batch_op.create_index(batch_op.f('ix_serenity_signals_extracted_at'), ['extracted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_serenity_signals_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_serenity_signals_tweet_id'), ['tweet_id'], unique=False)

    op.create_table('serenity_tweets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('quoted_id', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serenity_tweets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serenity_tweets_ingested_at'), ['ingested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_serenity_tweets_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_serenity_tweets_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_serenity_tweets_tweet_id'), ['tweet_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_tweets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serenity_tweets_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_serenity_tweets_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_serenity_tweets_posted_at'))
        batch_op.drop_index(batch_op.f('ix_serenity_tweets_ingested_at'))

    op.drop_table('serenity_tweets')
    with op.batch_alter_table('serenity_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serenity_signals_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_serenity_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_serenity_signals_extracted_at'))
        batch_op.drop_index('ix_serenity_signal_tweet_ticker')
        batch_op.drop_index('ix_serenity_signal_ticker_time')
        batch_op.drop_index('ix_serenity_signal_sentiment_time')

    op.drop_table('serenity_signals')
    with op.batch_alter_table('serenity_backtest', schema=None) as batch_op:
        batch_op.drop_index('ix_serenity_backtest_ticker_date')
        batch_op.drop_index(batch_op.f('ix_serenity_backtest_ticker'))
        batch_op.drop_index(batch_op.f('ix_serenity_backtest_signal_id'))

    op.drop_table('serenity_backtest')
    with op.batch_alter_table('discovery_serenity_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_serenity_score_total_desc')
        batch_op.drop_index(batch_op.f('ix_discovery_serenity_scores_auto_avoid'))

    op.drop_table('discovery_serenity_scores')
    # ### end Alembic commands ###
