"""add_serenity_price_gain_since_first_mention

Revision ID: 480206c08e21
Revises: f9de3d769f3d
Create Date: 2026-08-03 15:44:08.050791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480206c08e21'
down_revision: Union[str, Sequence[str], None] = 'f9de3d769f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_mention_date', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('first_mention_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gain_since_first_mention_pct', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.drop_column('gain_since_first_mention_pct')
        batch_op.drop_column('first_mention_price')
        batch_op.drop_column('first_mention_date')

    # ### end Alembic commands ###
