"""add_invalidation_hit_to_user_judgments

Revision ID: 5c83152af8da
Revises: 899bedc6eb64
Create Date: 2026-08-02 09:39:44.198100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c83152af8da'
down_revision: Union[str, Sequence[str], None] = '899bedc6eb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalidation_hit_ts', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invalidation_hit_low', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.drop_column('invalidation_hit_low')
        batch_op.drop_column('invalidation_hit_ts')

    # ### end Alembic commands ###
