"""add_entry_price_to_user_judgments

Revision ID: 5fb97fb52327
Revises: 5c83152af8da
Create Date: 2026-08-02 09:40:55.171524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb97fb52327'
down_revision: Union[str, Sequence[str], None] = '5c83152af8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.drop_column('entry_price')

    # ### end Alembic commands ###
