"""add_pk_asset_columns_and_tier_history

Revision ID: 730f31e9bbd9
Revises: f10d307fac0a
Create Date: 2026-07-30 15:25:30.570710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730f31e9bbd9'
down_revision: Union[str, Sequence[str], None] = 'f10d307fac0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powderkeg_tier_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('prev_tier', sa.String(length=30), nullable=True),
    sa.Column('curr_tier', sa.String(length=30), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('hypothesis_id', sa.String(length=50), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('powderkeg_tier_history', schema=None) as batch_op:
        batch_op.create_index('ix_pk_tier_hist_run', ['run_id'], unique=False)
        batch_op.create_index('ix_pk_tier_hist_ticker_time', ['ticker', 'changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_powderkeg_tier_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_powderkeg_tier_history_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_powderkeg_tier_history_ticker'), ['ticker'], unique=False)

    with op.batch_alter_table('powderkeg_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hypothesis_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_context', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('retrospect_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('conditions_margins_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_powderkeg_list_hypothesis_id'), ['hypothesis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powderkeg_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powderkeg_list_hypothesis_id'))
        batch_op.drop_column('conditions_margins_json')
        batch_op.drop_column('retrospect_url')
        batch_op.drop_column('market_context')
        batch_op.drop_column('hypothesis_id')

    with op.batch_alter_table('powderkeg_tier_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powderkeg_tier_history_ticker'))
        batch_op.drop_index(batch_op.f('ix_powderkeg_tier_history_run_id'))
        batch_op.drop_index(batch_op.f('ix_powderkeg_tier_history_changed_at'))
        batch_op.drop_index('ix_pk_tier_hist_ticker_time')
        batch_op.drop_index('ix_pk_tier_hist_run')

    op.drop_table('powderkeg_tier_history')
    # ### end Alembic commands ###
