"""add_sniper_api_access

Revision ID: 899bedc6eb64
Revises: 730f31e9bbd9
Create Date: 2026-07-31 10:21:54.865753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899bedc6eb64'
down_revision: Union[str, Sequence[str], None] = '730f31e9bbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sniper_api_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('token_source', sa.String(length=10), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sniper_api_access', schema=None) as batch_op:
        batch_op.create_index('ix_sniper_access_event_ts', ['event', 'ts'], unique=False)
        batch_op.create_index('ix_sniper_access_ip_ts', ['ip', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_sniper_api_access_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_sniper_api_access_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sniper_api_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sniper_api_access_ts'))
        batch_op.drop_index(batch_op.f('ix_sniper_api_access_event'))
        batch_op.drop_index('ix_sniper_access_ip_ts')
        batch_op.drop_index('ix_sniper_access_event_ts')

    op.drop_table('sniper_api_access')
    # ### end Alembic commands ###
