"""serenity_hunter_v6_step_a

Revision ID: 9fe06de4bdc6
Revises: bd80d13e57dd
Create Date: 2026-08-04 10:50:35.705994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe06de4bdc6'
down_revision: Union[str, Sequence[str], None] = 'bd80d13e57dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serenity_benchmark_prices',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'snapshot_date')
    )
    with op.batch_alter_table('serenity_benchmark_prices', schema=None) as batch_op:
        batch_op.create_index('ix_serenity_benchmark_symbol_date', ['symbol', 'snapshot_date'], unique=False)

    with op.batch_alter_table('serenity_backtest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_next_open_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('entry_with_slippage_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gap_next_open_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_1d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('return_3d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delisting_flag', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('benchmark_iwm_return_1d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_iwm_return_3d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_iwm_return_5d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_iwm_return_10d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_iwm_return_30d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_spy_return_1d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_spy_return_3d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_spy_return_5d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_spy_return_10d', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benchmark_spy_return_30d', sa.Float(), nullable=True))

    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_cap', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('market_cap_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avg_dollar_volume_20d', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.drop_column('avg_dollar_volume_20d')
        batch_op.drop_column('market_cap_source')
        batch_op.drop_column('market_cap')

    with op.batch_alter_table('serenity_backtest', schema=None) as batch_op:
        batch_op.drop_column('benchmark_spy_return_30d')
        batch_op.drop_column('benchmark_spy_return_10d')
        batch_op.drop_column('benchmark_spy_return_5d')
        batch_op.drop_column('benchmark_spy_return_3d')
        batch_op.drop_column('benchmark_spy_return_1d')
        batch_op.drop_column('benchmark_iwm_return_30d')
        batch_op.drop_column('benchmark_iwm_return_10d')
        batch_op.drop_column('benchmark_iwm_return_5d')
        batch_op.drop_column('benchmark_iwm_return_3d')
        batch_op.drop_column('benchmark_iwm_return_1d')
        batch_op.drop_column('delisting_flag')
        batch_op.drop_column('return_3d')
        batch_op.drop_column('return_1d')
        batch_op.drop_column('gap_next_open_pct')
        batch_op.drop_column('entry_with_slippage_price')
        batch_op.drop_column('entry_next_open_price')

    with op.batch_alter_table('serenity_benchmark_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_serenity_benchmark_symbol_date')

    op.drop_table('serenity_benchmark_prices')
    # ### end Alembic commands ###
