"""add_blue_chip_candidates_and_runs

Revision ID: af307f2c5e72
Revises: 5fb97fb52327
Create Date: 2026-08-02 10:13:58.629882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af307f2c5e72'
down_revision: Union[str, Sequence[str], None] = '5fb97fb52327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blue_chip_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('market_cap_krw', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('revenue_3y_growing', sa.Boolean(), nullable=False),
    sa.Column('net_income_3y_growing', sa.Boolean(), nullable=False),
    sa.Column('financial_years', sa.String(length=30), nullable=True),
    sa.Column('annual_turnaround', sa.Boolean(), nullable=False),
    sa.Column('annual_yoy_pcts', sa.String(length=80), nullable=True),
    sa.Column('monthly_ma5_above', sa.Boolean(), nullable=False),
    sa.Column('monthly_ma5_months_above', sa.Integer(), nullable=False),
    sa.Column('conditions_json', sa.Text(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('overall_pass', sa.Boolean(), nullable=False),
    sa.Column('reject_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blue_chip_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blue_chip_candidates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blue_chip_candidates_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blue_chip_candidates_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_bluechip_run_pass', ['run_id', 'overall_pass'], unique=False)
        batch_op.create_index('ix_bluechip_ticker_time', ['ticker', 'created_at'], unique=False)

    op.create_table('blue_chip_runs',
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('blue_chip_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blue_chip_runs_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blue_chip_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blue_chip_runs_started_at'))

    op.drop_table('blue_chip_runs')
    with op.batch_alter_table('blue_chip_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_bluechip_ticker_time')
        batch_op.drop_index('ix_bluechip_run_pass')
        batch_op.drop_index(batch_op.f('ix_blue_chip_candidates_ticker'))
        batch_op.drop_index(batch_op.f('ix_blue_chip_candidates_run_id'))
        batch_op.drop_index(batch_op.f('ix_blue_chip_candidates_created_at'))

    op.drop_table('blue_chip_candidates')
    # ### end Alembic commands ###
