"""add_serenity_price_sector_industry

Revision ID: bd80d13e57dd
Revises: 480206c08e21
Create Date: 2026-08-03 20:40:57.700587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd80d13e57dd'
down_revision: Union[str, Sequence[str], None] = '480206c08e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.drop_column('industry')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
