"""add_user_judgments

Revision ID: f10d307fac0a
Revises: 42970a316e10
Create Date: 2026-07-30 14:38:03.724658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10d307fac0a'
down_revision: Union[str, Sequence[str], None] = '42970a316e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_judgments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.String(length=50), server_default='owner', nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('page_source', sa.String(length=30), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=50), nullable=False),
    sa.Column('thesis_md', sa.Text(), nullable=False),
    sa.Column('invalidation_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=20), nullable=False),
    sa.Column('market_regime', sa.String(length=30), nullable=False),
    sa.Column('result_at_horizon', sa.Float(), nullable=True),
    sa.Column('result_computed_at', sa.DateTime(), nullable=True),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.create_index('ix_judgment_hyp_ts', ['hypothesis_id', 'ts'], unique=False)
        batch_op.create_index('ix_judgment_ticker_ts', ['ticker', 'ts'], unique=False)
        batch_op.create_index('ix_judgment_user_ts', ['user_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_judgments_hypothesis_id'), ['hypothesis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_judgments_page_source'), ['page_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_judgments_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_judgments_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_judgments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_judgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_judgments_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_judgments_ts'))
        batch_op.drop_index(batch_op.f('ix_user_judgments_ticker'))
        batch_op.drop_index(batch_op.f('ix_user_judgments_page_source'))
        batch_op.drop_index(batch_op.f('ix_user_judgments_hypothesis_id'))
        batch_op.drop_index('ix_judgment_user_ts')
        batch_op.drop_index('ix_judgment_ticker_ts')
        batch_op.drop_index('ix_judgment_hyp_ts')

    op.drop_table('user_judgments')
    # ### end Alembic commands ###
