"""add_serenity_ticker_prices

Revision ID: f9de3d769f3d
Revises: 2942cd845590
Create Date: 2026-08-03 10:49:49.027214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9de3d769f3d'
down_revision: Union[str, Sequence[str], None] = '2942cd845590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serenity_ticker_prices',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('prior_close', sa.Float(), nullable=True),
    sa.Column('vs_prior_close_pct', sa.Float(), nullable=True),
    sa.Column('yahoo_symbol', sa.String(length=20), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serenity_ticker_prices_snapshot_date'), ['snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serenity_ticker_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serenity_ticker_prices_snapshot_date'))

    op.drop_table('serenity_ticker_prices')
    # ### end Alembic commands ###
